"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

// One-time consent before any student text is sent to the AI provider
// (App Store guideline 5.1.2(i)). Until agreed, the hint ladder and tutor are
// replaced by this card; grading and the worked solution never need consent
// because they are deterministic and stay on the server.
const STORAGE_KEY = "anchor-ai-consent-v1";

export function useAiConsent(): [boolean | null, () => void] {
  const [consented, setConsented] = useState<boolean | null>(null);
  useEffect(() => {
    try {
      setConsented(window.localStorage.getItem(STORAGE_KEY) === "yes");
    } catch {
      setConsented(false);
    }
  }, []);
  const agree = () => {
    try {
      window.localStorage.setItem(STORAGE_KEY, "yes");
    } catch {
      // Consent still applies for this visit.
    }
    setConsented(true);
  };
  return [consented, agree];
}

export function AiConsentCard({ onAgree }: { onAgree: () => void }) {
  return (
    <section className="plane p-5" aria-label="AI tutor consent">
      <h2 className="font-display text-xl font-extrabold tracking-tight">
        Before the tutor can help
      </h2>
      <p className="mt-2 text-sm leading-relaxed">
        Hints and tutor replies are generated by an AI service (DeepSeek). To
        do that, the text of your attempts and your tutor messages for this
        problem are sent to it, along with the question. Nothing else is
        shared, and your marking never depends on the AI — answers are checked
        against a verified key by the app itself. Details in the{" "}
        <Link className="underline" href="/privacy">privacy policy</Link>.
      </p>
      <div className="mt-4 flex flex-wrap gap-2">
        <Button type="button" className="min-h-11" onClick={onAgree}>
          I understand — enable AI hints
        </Button>
      </div>
      <p className="mt-2 text-xs text-slate">
        Don&apos;t want AI involved? Keep attempting and use the worked
        solution after real work — everything else works without it.
      </p>
    </section>
  );
}
