import Link from "next/link";

export const metadata = { title: "Terms of use" };

export default function TermsPage() {
  return (
    <main className="mx-auto flex w-full max-w-2xl flex-col gap-6 px-4 py-10">
      <header>
        <h1 className="font-display text-3xl font-extrabold tracking-tight">
          Terms of use
        </h1>
        <p className="mt-2 text-sm text-slate">Effective 8 August 2026.</p>
      </header>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">The service</h2>
        <p className="mt-3 text-sm leading-relaxed">
          Anchor is a study tool: daily curriculum problems, spaced review and a
          tutor that makes you attempt first. It is a practice aid, not a
          replacement for your school, your teachers or an examination board.
          Using Anchor requires an account and is free of charge.
        </p>
      </section>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">Your account</h2>
        <ul className="mt-3 flex list-disc flex-col gap-2 pl-5 text-sm leading-relaxed">
          <li>You must be 13 or older to create an account.</li>
          <li>Keep your password to yourself; you are responsible for activity on your account.</li>
          <li>
            Pick a display name and avatar that are appropriate for classmates
            to see. Offensive names, impersonation or harassment of other
            players are not allowed and may lead to removal of content or the
            account.
          </li>
          <li>
            You can delete your account at any time from Profile → Settings —
            deletion is immediate and permanent.
          </li>
        </ul>
      </section>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">The AI tutor</h2>
        <p className="mt-3 text-sm leading-relaxed">
          Hints and tutor replies are generated by an AI model grounded in a
          verified answer key. They are designed to guide, not to answer, and
          like all AI output they can still be imperfect. Marking is done
          deterministically against the verified key, never by the AI. Do not
          rely on Anchor as your only source for exam preparation.
        </p>
      </section>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">Fair use</h2>
        <ul className="mt-3 flex list-disc flex-col gap-2 pl-5 text-sm leading-relaxed">
          <li>No attempting to break, probe or overload the service.</li>
          <li>No scraping other players&apos; data.</li>
          <li>No automating attempts to farm XP or leaderboard positions.</li>
        </ul>
      </section>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">Liability</h2>
        <p className="mt-3 text-sm leading-relaxed">
          Anchor is provided &quot;as is&quot;, without warranties. To the
          fullest extent permitted by law, we are not liable for indirect
          losses, lost data caused by events outside our control, or exam
          outcomes. Nothing in these terms limits liability that cannot be
          limited by law.
        </p>
      </section>

      <section className="plane p-6">
        <h2 className="font-display text-xl font-extrabold">Changes and contact</h2>
        <p className="mt-3 text-sm leading-relaxed">
          If these terms change materially we will say so in the app. Questions:{" "}
          <a className="underline" href="mailto:zuki200912345@gmail.com">
            zuki200912345@gmail.com
          </a>
          . See also the{" "}
          <Link className="underline" href="/privacy">privacy policy</Link> and{" "}
          <Link className="underline" href="/support">support</Link>.
        </p>
      </section>
    </main>
  );
}
